#### Lesson 7. Intro to NumPy
##### Date: 11.07.23

**Topics**:
> 1. Numpy intro
> 2. Vector/Matrix/Tensor
> 3. Vector math
> 4. Filter array(boolen mask, where)
> 5. SQlite3

**Materials**:
> 1. [NumPy](https://www.w3schools.com/python/numpy/numpy_intro.asp)
> 2. [NumPy doc](https://numpy.org/doc/stable/user/absolute_beginners.html)
> 3. [Tutorial](https://www.tutorialspoint.com/numpy/numpy_introduction.htm)
> 4. [Sqlite3](https://docs.python.org/3/library/sqlite3.html)

>**NumPy** - це бібліотека для мови програмування Python, призначена для виконання обчислювальних завдань на багатовимірних масивах або матрицях.

> NumPy дозволяє створювати масиви даних будь-якого розміру, а також виконувати операції з ними, такі як математичні операції, зрізи, індексування та багато іншого. Вона також надає функції для лінійної алгебри, статистичного аналізу, перетворення Фур'є та багатьох інших алгоритмів.

> Використання NumPy в Python дозволяє швидко та зручно обробляти великі обсяги даних та прискорює виконання математичних операцій. Вона також може бути використана разом з іншими бібліотеками Python для створення наукових додатків та інструментів.

NumPy - написаний на С, в основу покладені наступні бібліотеки: **BLAS**, **LAPACK** - Fortran

Install Numpy:

Conda: 
**conda install numpy**

Pip-pip3:
**pip install numpy**

In [10]:
import numpy as np # імпорт функціоналу та даємо псевдонім 
import matplotlib.pyplot as plt 
import seaborn as sns
# from numpy import arange, stack, ethc

Python list:
1. Save information different type 

Numpy array: 
1. Save inforamtion one type
2. Less memory 
3. Fast math operation

In [11]:
list1 = [[1,2,3, 4], [5, 6, 7, 8]]
arr = np.array([[1,2,3, 4], [5, 6, 7, 8]])
print(list1, list1.__sizeof__(), end = '\n\n')
print(arr, arr.__sizeof__())

[[1, 2, 3, 4], [5, 6, 7, 8]] 56

[[1 2 3 4]
 [5 6 7 8]] 192


In [12]:
# Vector - one dim array 
vector = np.array([1,2,3,4,5])
print(vector, vector.shape)
print(vector.reshape(-1,1),vector.reshape(-1,1).shape)

[1 2 3 4 5] (5,)
[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)


In [15]:
# Matrix - two dim array, n * m - table , rows * columns = mat
arr = np.array([[1,2,3, 4], [5, 6, 7, 8]])
print(f'Array: {arr}\nShape: {arr.shape}', end = '\n\n')
print(arr.reshape(4, 2), arr.reshape(1, 8))

# Квадратая матрица - row = column , 2x2, 3x3, 4x4, etc rows = columns
arr1 = np.array([[1,2], [5, 6]])
print(f'Array: {arr1}\nShape: {arr1.shape}')

Array: [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] [[1 2 3 4 5 6 7 8]]
Array: [[1 2]
 [5 6]]
Shape: (2, 2)


In [16]:
# Tensor - многомірна matrix
arr = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
])
print(f'Array: {arr}\nShape: {arr.shape}')

Array: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


![](https://miro.medium.com/v2/resize:fit:957/1*jRyyMAhS_NZxqyv3EoLCvg.png)

![](https://editor.analyticsvidhya.com/uploads/64798tensor.png)

In [17]:
# Zeros - create zero array
zero = np.zeros(5)
print(zero)
zero_2d = np.zeros((2, 5)) # arg - tuple, where first arg - row, second - column
print(zero_2d)
zero_3d = np.zeros((2, 5, 2))
print(zero_3d)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [11]:
# Ones - create one-value matrix
arr = np.ones((3,4)) # tuple: [0] - row, [1] - columns
print(arr, arr.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)


In [22]:
# Arange - generate vector
arr = np.arange(1, 13) # range - start, end, step
print(arr, arr.shape)

arr1 = np.arange(1, 13).reshape(3, 4) # 2d - matrix
print(arr1, arr1.shape, arr1.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 12


In [22]:
# Linspace - рівномірний розподіл
arr = np.linspace(0, 1, 10) # three arg - start, end, count of values
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
dir(arr)[96:] # check all methods

['any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

In [26]:
arr_bool = np.array([True, False, True, False, False])
print(arr_bool) # Bool

arr_float = np.array([True, 3.14, 1, 15, False])
print(arr_float) # Float

arr_string = np.array(['String', 3.14, 15, False, True])
print(arr_string) # String

[ True False  True False False]
[ 1.    3.14  1.   15.    0.  ]
['String' '3.14' '15' 'False' 'True']


In [35]:
# to create with dtype, use dtype 
arr_uint8 = np.arange(1, 12, dtype= np.uint8) # unsig type
print(arr_uint8, arr_uint8.dtype)

arr_float32 = np.array([1,2,3,4, 5.14, False, True, -17], dtype= np.float32)
print(arr_float32, arr_float32.dtype, arr_uint8.size)

[ 1  2  3  4  5  6  7  8  9 10 11] uint8
[  1.     2.     3.     4.     5.14   0.     1.   -17.  ] float32 11


In [30]:
# Astype - convert data type
arr1 = np.array([9, 12, True, 3.13]).astype('<U5') # string Unicode
arr2 = np.array([9, 12, True, 3.13, 'Numpy']) # string
arr3 = np.array([9, 12, True, 3.13]).astype(np.uint16) # +int
arr4 = np.array([9, 12, True, 3.13]).astype(np.int64)  # int
arr5 = np.random.random((3,4))
arr6 = np.array([[1,2,3], [4,5,6.0], [7, 8, 9]])

for i in range(1, 7):
    print(eval(f'arr{i}'))
    print(eval(f'arr{i}.dtype'), end = '\n\n') # <U - unicode with len

['9.0' '12.0' '1.0' '3.13']
<U5

['9' '12' 'True' '3.13' 'Numpy']
<U32

[ 9 12  1  3]
uint16

[ 9 12  1  3]
int64

[[0.12823728 0.305058   0.42770077 0.96585331]
 [0.99626675 0.34956935 0.42533657 0.46964557]
 [0.09275504 0.04345679 0.60176075 0.06913091]]
float64

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64



In [33]:
np.random.randint(5, 10, size = 10)

array([8, 9, 5, 8, 7, 5, 8, 5, 8, 6])

> numpy.add(x1, x2) - додавання двох векторів \
> numpy.subtract(x1, x2) - віднімання одного вектора з іншого \
> numpy.multiply(x1, x2) - поелементне множення двох векторів \
> numpy.divide(x1, x2) - поелементне ділення одного вектора на інший \
> numpy.dot(x1, x2) - скалярний добуток двох векторів \

In [37]:
# Vector math 
x1 = np.array([1, 2, 3])
x2 = np.array([4, 5,6])
print(f'Add: {x1 + x2} or {np.add(x1, x2)}')
print(f'Subtract: {x1 - x2} or {np.subtract(x1, x2)}')
print(f'Multiply: {x1 * x2} or {np.multiply(x1, x2)}')
print(f'Divide: {x1 / x2} or {np.divide(x1, x2)}')
print(f'Dot: {np.dot(x1, x2)}')
print(f'Multiply by number: {x1 * 3}')

Add: [5 7 9] or [5 7 9]
Subtract: [-3 -3 -3] or [-3 -3 -3]
Multiply: [ 4 10 18] or [ 4 10 18]
Divide: [0.25 0.4  0.5 ] or [0.25 0.4  0.5 ]
Dot: 32
Multiply by number: [3 6 9]


#### Index and Slicing 
basic: [start: stop: steps] \
n-d index: [start:stop:steps][start:stop:steps]


In [38]:
arr = np.array([[1,2,3, 4], [5, 6, 7, 8]])
# arr[refers to axis 0(rows), refers to axis 1 (columns)]
print(arr, arr[0, :], arr[:, 1], arr.shape, sep= '\n\n') # [][]

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]

[2 6]

(2, 4)


Filtering data in numpy:
> 1. Fancy index with boolen mask - **return array of elements**
> 2. where - **return index**

In [43]:
# & - логічне так(and)
# | - логічне або(or)- pipe
# ~ - логічне ні(not)
arr = np.array([[1,2,3, 4], [5, 6, 7, 8], [9,10,11,12]])

even_number = arr % 2 == 0 # Arr true/false
print(even_number, arr[~even_number], arr[~(arr % 2 == 0) & (arr > 5)], end = '\n\n')

big_mean = arr > arr.mean()
print(big_mean, arr[big_mean], end = '\n\n')

[[False  True False  True]
 [False  True False  True]
 [False  True False  True]] [ 1  3  5  7  9 11] [ 7  9 11]

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]] [ 7  8  9 10 11 12]



#### Comdine diff statemens
> **&** - логічне та  \
> **|** - логічне або \
> **~** - логічні ні

In [18]:
two_statemnt = (arr > 2) & (arr < 10)
print(two_statemnt, arr[two_statemnt], end = '\n\n')

two_statemnt = (arr > 2) | (arr != 10)
print(two_statemnt, arr[two_statemnt], end = '\n\n')

print(arr[(arr % 2 == 0) & (arr < 10)]) # or you write in []

[[False False  True  True]
 [ True  True  True  True]
 [ True False False False]] [3 4 5 6 7 8 9]

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] [ 1  2  3  4  5  6  7  8  9 10 11 12]

[2 4 6 8]


In [96]:
arr.shape[0]

2

In [61]:
# Task 1. Create list with 50 elements, reshape in 3 - var
# 10x5, 25x2, 5x10, 2x25, 1x50, 2x5x5 - arange/randint 
arr = np.arange(1, 51, dtype = np.uint16)
print(arr.reshape((10, 5)), arr.reshape((2, 25)), arr.reshape((1, 50)), sep= '\n\n' )
# Task 2. Find elements, where elements more than 20 and less 30 
print(arr[(arr > 20) & (arr < 30)])
# Task 3. Find elements, where elements is even 
print(arr[~arr % 2 == 1])
# Task 4. Generate chess dashboard - elem 
print(np.zeros((8, 8)))
# Task 5. Find elements, where elements is NOT even, less than 41 and more then 15 and elements not equal 21
print(arr[(arr % 2 != 0) & ((arr > 15) & (arr < 41)) & (arr != 21)])
# Task 6. Find sum of diagonal for matrix (5, 5). Step 1: generate matrix. Step 2: display diagonal, Step 3: Find sum of main dianogal, Step 3: Find alternative diagonal, find elements what more than sum of main diagonal 
# - elem diagonal

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25]
 [26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
  50]]

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49 50]]
[21 22 23 24 25 26 27 28 29]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[17 19 23 25 27 29 31 33 35 37 39]


In [52]:
arr = np.arange(1, 26).reshape((5,5))

In [55]:
arr

SyntaxError: invalid syntax (1582438860.py, line 1)

Where - function 
numpy.where(condition[, x, y])


In [62]:
print(arr)
print(np.where(arr == 4)) # return position(index)
print(np.where(arr % 2 == 0))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
(array([3]),)
(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49]),)


In [64]:
print(arr)
print(np.where(arr % 2 == 0,arr, 'Not True')) # three args: condit, array, default value

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
['Not True' '2' 'Not True' '4' 'Not True' '6' 'Not True' '8' 'Not True'
 '10' 'Not True' '12' 'Not True' '14' 'Not True' '16' 'Not True' '18'
 'Not True' '20' 'Not True' '22' 'Not True' '24' 'Not True' '26'
 'Not True' '28' 'Not True' '30' 'Not True' '32' 'Not True' '34'
 'Not True' '36' 'Not True' '38' 'Not True' '40' 'Not True' '42'
 'Not True' '44' 'Not True' '46' 'Not True' '48' 'Not True' '50']


In [65]:
arr = np.array([[1,2,3, 4], [5, 6, 7, 8]])
print(arr, end = '\n\n')
print(arr.flatten(), end = '\n\n') # to one dimension, сплющує в одномірний массив, але при цьому створює копію 
print(arr.ravel()) # to one dimension, не створює копію

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8]

[1 2 3 4 5 6 7 8]


In [12]:
arr = np.arange(1, 65)
print(arr) 

print(arr.reshape((8,8)), arr.reshape((32,2)), sep = '\n\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]
 [25 26]
 [27 28]
 [29 30]
 [31 32]
 [33 34]
 [35 36]
 [37 38]
 [39 40]
 [41 42]
 [43 44]
 [45 46]
 [47 48]
 [49 50]
 [51 52]
 [53 54]
 [55 56]
 [57 58]
 [59 60]
 [61 62]
 [63 64]]


In [66]:
help(np.ravel)

Help on function ravel in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
    
    A 1-D array, containing the elements of the input, is returned.  A copy is
    made only if needed.
    
    As of NumPy 1.10, the returned array will have the same type as the input
    array. (for example, a masked array will be returned for a masked array
    input)
    
    Parameters
    ----------
    a : array_like
        Input array.  The elements in `a` are read in the order specified by
        `order`, and packed as a 1-D array.
    order : {'C','F', 'A', 'K'}, optional
    
        The elements of `a` are read using this index order. 'C' means
        to index the elements in row-major, C-style order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest.  'F' means to index the elements
        in column-major, Fortran-style order, with the
        first index changing fastest, and the last index changing
       

In [65]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [62]:
print(arr.reshape(4, 2)) # change size 
print(arr.shape[0], arr.shape[1],  arr.size)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2 4 8


In [ ]:
print(arr.dtype)

In [ ]:
one_to_ten = np.arange(1, 11)

plt.scatter(x = one_to_ten, y = one_to_ten * 2)
plt.show()

In [ ]:
arr3d = np.array([[1,2,3, 4], [5, 6, 7, 8], [9, 10, 11, 22]])
print(arr3d, arr3d.shape)
print(arr3d.reshape(1, 2, 6))

#### Concatenate : join arrays, use axis
numpy.concatenate((a1, a2, ...), axis=0)


![](https://pyprog.pro/images/2nd_array.jpg)

![](https://pyprog.pro/images/3nd_array.jpg)

In [66]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 

In [67]:
arr1 = np.arange(1, 5)
arr2 = np.arange(5, 10)

In [68]:
print(arr1, arr2)
arr_concate = np.concatenate((arr1, arr2))
print(arr_concate)

[1 2 3 4] [5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [69]:
arr1 = np.array([[1,2,3], [4,5, 6]])
arr2 = np.array([[2,3, 4], [7,8,9]])

In [71]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
arr2

array([[2, 3, 4],
       [7, 8, 9]])

In [70]:
arr_concate = np.concatenate((arr1, arr2)) # Join array
print(arr_concate)

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [7 8 9]]


#### Stack - використовується для об'єднання масивів уздовж нової осі
numpy.stack(arrays, axis=0)
> 1. **hstack** - використовується для горизонтальної конкатенації (об'єднання) двох або більше масивів вздовж другої осі (осі 1) - тобто об'єднання елементів рядків.
> 2. **vstack** - використовується для вертикальної конкатенації (об'єднання) двох або більше масивів вздовж першої осі (осі 0) - тобто об'єднання елементів стовпців.
> 3. **dstack** використовується для об'єднання двох або більше масивів вздовж третьої осі (ось 2) - тобто об'єднання елементів у глибину


In [73]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a3 = np.array([7, 8, 9])
print(a1,a2,a3)
result = np.stack((a1, a2, a3), axis=1)

print(result)
#  display:
# [[1 4 7]
#  [2 5 8]
#  [3 6 9]]


[1 2 3] [4 5 6] [7 8 9]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [74]:
# Hstack 
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(np.hstack((a1, a2)))

[1 2 3 4 5 6]


In [75]:
# Vstack
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

print(np.vstack((a1, a2)))

[[1 2 3]
 [4 5 6]]


In [76]:
# Dstack
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])

print(np.dstack((a1, a2)))

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [77]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2))
print(arr, ) # axis add 

print(np.hstack((arr1, arr2)))
print(np.vstack((arr1, arr2)))
print(np.dstack((arr1, arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


#### Array_split - function to split array multiple sub-arrays of equal or near-equal size.

In [78]:
arr = np.arange(1, 12)
new_arr = np.array_split(arr, 3) # розбити на підмассиви
print(new_arr)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11])]


In [79]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
result = np.array_split(arr, 3)
print(result)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


#### Sort - function return sorted copy

In [81]:
arr = np.array([[3, 2, 4], [6, 5, 1]])
arr

array([[3, 2, 4],
       [6, 5, 1]])

In [86]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x1122edb40>
File:            /usr/local/lib/python3.10/site-packages/numpy/core/fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, opti

In [89]:
result = np.sort(arr, axis=1,  kind = 'mergesort')[::-1]
print(result)

[[1 5 6]
 [2 3 4]]


In [90]:
arr

array([[3, 2, 4],
       [6, 5, 1]])

In [94]:
np.sum(arr, axis = 1)

array([ 9, 12])

In [91]:
np.sum(arr)

21

In [92]:
np.max(arr, axis = 1)

array([4, 6])

In [93]:
np.mean(arr, axis = 0)

array([4.5, 3.5, 2.5])

### ORM 

In [3]:
# Connect with BD 
import sqlite3

# create a connection to the database
conn = sqlite3.connect('example.db')

print(conn)
# create a table
conn.execute('''CREATE TABLE IF NOT EXISTS
             users (id INTEGER PRIMARY KEY, name TEXT)''')

# commit the changes
conn.commit()

# close the connection
conn.close()


In [2]:
from faker import Faker

fake = Faker()

for i in range(1, 10):
    print(fake.first_name())

Andrea
Dennis
Shaun
Mariah
Destiny
Tonya
Amanda
Anthony
Richard


In [4]:
from faker import Faker

fake = Faker()

Faker.seed(42)

conn = sqlite3.connect('example.db')

for i in range(1, 120):
    conn.execute("INSERT INTO users (id, name) VALUES (?, ?)", (i, fake.name()))

conn.commit()

# close the connection
conn.close()

In [9]:
# create a connection to the database
conn = sqlite3.connect('example.db')

# retrieve data from the table
cursor = conn.execute("SELECT id, name FROM users")

In [7]:
cursor.fetchall()

[(1, 'Allison Hill'),
 (2, 'Noah Rhodes'),
 (3, 'Angie Henderson'),
 (4, 'Daniel Wagner'),
 (5, 'Cristian Santos'),
 (6, 'Connie Lawrence'),
 (7, 'Abigail Shaffer'),
 (8, 'Gina Moore'),
 (9, 'Gabrielle Davis'),
 (10, 'Ryan Munoz'),
 (11, 'Monica Herrera'),
 (12, 'Jamie Arnold'),
 (13, 'Lisa Hensley'),
 (14, 'Michele Williams'),
 (15, 'Dylan Miller'),
 (16, 'Brian Ramirez'),
 (17, 'Holly Wood'),
 (18, 'Derek Zuniga'),
 (19, 'Lisa Jackson'),
 (20, 'Carla Gray'),
 (21, 'Margaret Hawkins DDS'),
 (22, 'Patty Perez'),
 (23, 'Ethan Adams'),
 (24, 'Tommy Walter'),
 (25, 'Matthew Foster'),
 (26, 'Judy Baker'),
 (27, 'Justin Baker'),
 (28, 'Stephanie Ross'),
 (29, 'Zachary Hicks'),
 (30, 'Anthony Rodriguez'),
 (31, 'Rebecca Henderson'),
 (32, 'James Ferrell'),
 (33, 'Tricia Valencia'),
 (34, 'Nathan Maldonado'),
 (35, 'Debra Davidson'),
 (36, 'Jeffrey Chavez'),
 (37, 'Sherri Baker'),
 (38, 'Cassandra Gaines'),
 (39, 'Elizabeth Fowler'),
 (40, 'Brittany Farmer'),
 (41, 'Paula Moreno'),
 (42, 'Fre

In [10]:
rows = cursor.fetchall() # fetchone
print(rows)

# print the data
for row in rows:
    print(row)

# close the connection
conn.close()

[(1, 'Allison Hill'), (2, 'Noah Rhodes'), (3, 'Angie Henderson'), (4, 'Daniel Wagner'), (5, 'Cristian Santos'), (6, 'Connie Lawrence'), (7, 'Abigail Shaffer'), (8, 'Gina Moore'), (9, 'Gabrielle Davis'), (10, 'Ryan Munoz'), (11, 'Monica Herrera'), (12, 'Jamie Arnold'), (13, 'Lisa Hensley'), (14, 'Michele Williams'), (15, 'Dylan Miller'), (16, 'Brian Ramirez'), (17, 'Holly Wood'), (18, 'Derek Zuniga'), (19, 'Lisa Jackson'), (20, 'Carla Gray'), (21, 'Margaret Hawkins DDS'), (22, 'Patty Perez'), (23, 'Ethan Adams'), (24, 'Tommy Walter'), (25, 'Matthew Foster'), (26, 'Judy Baker'), (27, 'Justin Baker'), (28, 'Stephanie Ross'), (29, 'Zachary Hicks'), (30, 'Anthony Rodriguez'), (31, 'Rebecca Henderson'), (32, 'James Ferrell'), (33, 'Tricia Valencia'), (34, 'Nathan Maldonado'), (35, 'Debra Davidson'), (36, 'Jeffrey Chavez'), (37, 'Sherri Baker'), (38, 'Cassandra Gaines'), (39, 'Elizabeth Fowler'), (40, 'Brittany Farmer'), (41, 'Paula Moreno'), (42, 'Fred Smith'), (43, 'Sherry Decker'), (44, 'A

In [53]:
conn.close()

In [22]:
with sqlite3.connect('example.db') as conn:
    # create a cursor
    cursor = conn.cursor()

    # create a table
    # cursor.execute('''CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT)''')

    # insert some data
    #cursor.execute("INSERT INTO users (id, name) VALUES (21, 'Alice')")
    #cursor.execute("INSERT INTO users (id, name) VALUES (22, 'Bob')")

    # commit the changes
    # conn.commit()

    # retrieve data from the tableike '
    cursor.execute("SELECT  id, name FROM users WHERE length(name) = 15 ORDER BY id DESC")
    rows = cursor.fetchmany(10) #fetchall, fetchone

    # _ - один символ 
    # % - будь-яку символ
    # print the data
    for row in rows:
        print(row)

(117, 'William Herrera')
(114, 'Crystal Johnson')
(92, 'Brian Rodriguez')
(85, 'Zachary Ferrell')
(61, 'Victoria Garcia')
(58, 'Richard Aguirre')
(48, 'Shane Henderson')
(45, 'Angelica Tucker')
(40, 'Brittany Farmer')
(33, 'Tricia Valencia')


In [ ]:
# Task 1. Знайти всіх людей у кого на 3 позиції є літера f
# Task 2. Знайти всіх людей у кого всього 14 символів імя 
# Task 3. Знайти всіх людей у кого id < 50 

In [72]:
with sqlite3.connect('example.db') as conn:
    
    cursor = conn.cursor()
    
    cursor.execute('''SELECT name FROM sqlite_master where type = 'table' ''')
    
    result = cursor.fetchall()
    
    for i in result:
        print(i)

('users',)
('person',)


In [71]:
with sqlite3.connect('example.db') as conn:
    cursor = conn.cursor()
    cursor.execute('''CREATE TABLE person (id INTEGER PRIMARY KEY, name TEXT, surname TEXT)''')
    
    for i in range(1, 16):
        conn.execute("INSERT INTO person (id, name, surname) VALUES (?, ?, ?)", (i, fake.first_name(), fake.last_name()))

    conn.commit()

    cursor.execute("SELECT id, name, surname FROM person")
    rows = cursor.fetchall()

    for row in rows:
        print(row)

(1, 'Jeffrey', 'Doyle')
(2, 'Erica', 'Mcclain')
(3, 'Christopher', 'Henderson')
(4, 'Anthony', 'Robinson')
(5, 'William', 'Johnson')
(6, 'James', 'Santos')
(7, 'Amy', 'Robinson')
(8, 'Bridget', 'Pacheco')
(9, 'Adam', 'Shaffer')
(10, 'Helen', 'Peterson')
(11, 'Eric', 'Bernard')
(12, 'Matthew', 'Davis')
(13, 'Colin', 'Abbott')
(14, 'Cassandra', 'Roman')
(15, 'Jessica', 'Herrera')


In [ ]:
# Sqlite3 - create table person, with id: int, primary key, name: text, surname: text 
# заповнити 15 кортежі, use - faker, use - context manager